import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { runMigrations } from "../src/lib/db/migrate";
import { createRepositories } from "../src/lib/db/repositories";
import { orderedScenes, probeMp4, sceneOutputDurationMs, stitchTrailer } from "../src/lib/media/stitcher";
import { MockTtsProvider } from "../src/lib/tts/mock-provider";
import { MockVideoProvider } from "../src/lib/video/mock-provider";

function setup() { const database = new Database(":memory:"); runMigrations(database); const repo = createRepositories(database); const project = repo.createProject({ title: "Render test", synopsis: "One. Two.", genre: "Drama", languageCode: "en-IN" }); const first = repo.createScene(project.id, { sceneNumber: 1, exactText: "One." }); const second = repo.createScene(project.id, { sceneNumber: 2, exactText: "Two." }); return { database, repo, project, first, second }; }
function approve(repo: ReturnType<typeof createRepositories>, sceneId: string, media = false) { repo.createAudioVersion({ sceneId, provider: "mock", model: "fixture", audioPath: `projects/test/audio/${sceneId}.wav`, durationMs: 1_000 }); repo.approveTts(sceneId); if (media) { const version = repo.createSceneVersion({ sceneId, provider: "manual", prompt: "Shot", negativePrompt: "", videoPath: `projects/test/videos/${sceneId}.mp4`, durationMs: 2_200, status: "READY" }); repo.approveSceneVersion(version.id); } }

test("render readiness requires one approved narration and one approved video for each scene", () => { const { database, repo, project, first, second } = setup(); approve(repo, first.id, true); approve(repo, second.id); assert.deepEqual(repo.getRenderReadiness(project.id).missingSceneIds, [second.id]); const extra = repo.createAudioVersion({ sceneId: first.id, provider: "mock", model: "fixture", audioPath: "extra.wav", durationMs: 1_000 }); assert.equal(extra.status, "READY"); approve(repo, second.id, true); assert.equal(repo.getRenderReadiness(project.id).ready, true); database.close(); });
test("scene ordering and duration matching use scene number and approved audio plus breathing room", () => { assert.deepEqual(orderedScenes([{ sceneNumber: 3 }, { sceneNumber: 1 }, { sceneNumber: 2 }]).map((scene) => scene.sceneNumber), [1, 2, 3]); assert.equal(sceneOutputDurationMs({ audioDurationMs: 1_000, targetDurationMs: 2_200 }), 2_200); assert.equal(sceneOutputDurationMs({ audioDurationMs: 3_000, targetDurationMs: 2_200 }), 3_000); });
test("render attempts are versioned and preserve failed and successful states", () => { const { database, repo, project } = setup(); const first = repo.createRenderVersion(project.id); const failed = repo.updateRenderVersion(first.id, { status: "FAILED", completedAt: new Date().toISOString(), errorMessage: "FFmpeg failed" }); assert.equal(failed?.status, "FAILED"); const second = repo.createRenderVersion(project.id); const complete = repo.updateRenderVersion(second.id, { status: "COMPLETE", completedAt: new Date().toISOString(), outputPath: "projects/test/renders/final-v2.mp4", durationMs: 4_200 }); assert.equal(second.versionNumber, 2); assert.equal(complete?.status, "COMPLETE"); assert.equal(repo.getLatestRenderVersion(project.id)?.outputPath, "projects/test/renders/final-v2.mp4"); database.close(); });
test("fixture media stitches into a validated vertical H.264/AAC MP4", async (t) => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "pocketframe-render-")); const prior = process.env.POCKETFRAME_DATA_DIR; process.env.POCKETFRAME_DATA_DIR = root; t.after(() => { if (prior === undefined) delete process.env.POCKETFRAME_DATA_DIR; else process.env.POCKETFRAME_DATA_DIR = prior; fs.rmSync(root, { recursive: true, force: true }); }); const videoPath = "projects/fixture/videos/scene.mp4"; const audioPath = "projects/fixture/audio/scene.wav"; const tts = new MockTtsProvider(); await tts.synthesize({ exactText: "A quiet promise.", performancePrompt: "", outputPath: path.join(root, audioPath), languageCode: "en-IN", quality: "preview" }); const video = new MockVideoProvider(); await video.submit({ sceneId: "scene", versionNumber: 1, prompt: "", negativePrompt: "", targetDurationMs: 1_000, outputPath: path.join(root, videoPath) }); assert.ok(fs.existsSync(path.join(root, videoPath))); const result = await stitchTrailer({ projectId: "fixture", renderVersion: 1, title: "Fixture", tagline: "A quiet promise", cta: "Listen now on Pocket FM", subtitles: false, scenes: [{ sceneId: "scene", sceneNumber: 1, exactText: "A quiet promise.", videoPath, audioPath, audioDurationMs: 1_200, targetDurationMs: 2_400 }] }); assert.equal(result.mockFallback, false); const probe = await probeMp4(path.join(root, result.outputPath)); assert.equal(probe.videoCodec, "h264"); assert.equal(probe.audioCodec, "aac"); assert.equal(probe.width, 1080); assert.equal(probe.height, 1920); assert.ok(Math.abs(probe.durationMs - 4_200) < 1_000, `actual duration: ${probe.durationMs}`); });
