import Link from "next/link";
import { notFound } from "next/navigation";
import { repositories } from "@/lib/db";
import { WorkspaceStepper } from "@/components/workspace-stepper";
import { StoryPlanningSetup } from "@/components/story-planning-setup";
import { VoiceSceneCards } from "@/components/voice-scene-cards";
import { ShotSceneCards } from "@/components/shot-scene-cards";
import { FinalCutPanel } from "@/components/final-cut-panel";
export default async function ProjectWorkspace({ params }: { params: Promise<{ projectId: string }> }) {
  const project = repositories().getProject((await params).projectId); if (!project) notFound();
  const scenes = repositories().listScenes(project.id);
  const voiceActive = ["VOICE_REVIEW", "READY_TO_RENDER", "RENDERING", "COMPLETE"].includes(project.status);
  const shotsActive = ["SHOT_GENERATION", "SHOT_REVIEW", "VOICE_REVIEW", "READY_TO_RENDER", "RENDERING", "COMPLETE"].includes(project.status);
  const audioVersions = Object.fromEntries(scenes.map((scene) => [scene.id, repositories().listAudioVersions(scene.id)]));
  const versions = Object.fromEntries(scenes.map((scene) => [scene.id, repositories().listSceneVersions(scene.id)])); const readiness = repositories().getRenderReadiness(project.id); const render = repositories().getLatestRenderVersion(project.id);
  const current = project.status === "COMPLETE" || project.status === "RENDERING" || project.status === "READY_TO_RENDER" ? "Final Cut" : voiceActive ? "Voice" : shotsActive ? "Shots" : "Story";
  const status = project.status.split("_").map((word) => word[0] + word.slice(1).toLowerCase()).join(" ");
  const progress = scenes.length ? Math.round(((scenes.filter((scene) => scene.approvedVersionId).length + (voiceActive ? scenes.filter((scene) => scene.status !== "DRAFT").length : 0)) / (scenes.length * 2)) * 100) : 0;
  return <div className="workspace-shell"><header className="app-header"><Link className="brand" href="/"><span className="brand-mark">PF</span><span>PocketFrame <small>AI TRAILER STUDIO</small></span></Link><nav className="floating-navigation" aria-label="Project navigation"><a className={current === "Story" ? "active" : ""} href="#story">Story</a><a className={current === "Voice" ? "active" : ""} href="#voice">Voice</a><a className={current === "Shots" ? "active" : ""} href="#shots">Shots</a><a className={current === "Final Cut" ? "active" : ""} href="#final-cut">Final Cut</a></nav><div className="header-project"><span className="status-badge status-neutral">{status}</span><strong>{project.title}</strong></div></header><main className="workspace-content"><header className="workspace-header"><div><p className="eyebrow">Production workspace</p><h1>{current}</h1><p>{current === "Story" ? "Shape the editorial production bible and visual sequence." : current === "Voice" ? "Generate the exact narration after silent visuals are approved." : current === "Shots" ? "Review visual versions — every source clip stays silent." : "Assemble approved visual and narration masters for export."}</p></div><div className="header-progress"><span>Project progress</span><strong>{progress}%</strong><div className="progress-track"><i style={{ width: `${progress}%` }} /></div><span className="status-badge status-neutral">{status}</span></div></header><WorkspaceStepper current={current} /><section className="project-overview"><div className="section-heading"><div><p className="eyebrow">Story source</p><h2>Original synopsis</h2></div><div className="overview-meta"><span>{project.genre}</span><span>{project.languageCode}</span></div></div><p className="synopsis">{project.synopsis}</p></section><StoryPlanningSetup projectId={project.id} productionBible={project.productionBible} scenes={scenes} status={project.status} />{shotsActive && <ShotSceneCards scenes={scenes} versions={versions} />}{voiceActive && <VoiceSceneCards scenes={scenes} audioVersions={audioVersions} voiceBible={project.voiceBible} />}<FinalCutPanel projectId={project.id} title={project.title} scenes={scenes} ready={readiness.ready} render={render} /></main></div>;
}
