"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { RenderVersion, Scene } from "@/lib/db/repositories";
export function FinalCutPanel({ projectId, title, scenes, ready, render }: { projectId: string; title: string; scenes: Scene[]; ready: boolean; render?: RenderVersion }) {
  const router = useRouter(); const [working, setWorking] = useState(false); const [error, setError] = useState<string>(); const [subtitles, setSubtitles] = useState(false); const [music, setMusic] = useState<File>(); const musicRef = useRef<HTMLInputElement>(null);
  const approvedVoices = scenes.filter((scene) => scene.status === "TTS_APPROVED" || ["VIDEO_QUEUED", "VIDEO_GENERATING", "VIDEO_REVIEW", "APPROVED"].includes(scene.status)).length; const approvedScenes = scenes.filter((scene) => scene.approvedVersionId).length;
  async function renderTrailer() { setWorking(true); setError(undefined); const form = new FormData(); form.set("title", title); form.set("cta", "Listen now on Pocket FM"); form.set("subtitles", String(subtitles)); if (music) form.set("music", music); const response = await fetch(`/api/projects/${projectId}/render`, { method: "POST", body: form }); const data = await response.json().catch(() => ({})); setWorking(false); if (!response.ok) setError(data.error?.message ?? "Render failed."); else router.refresh(); }
  const status = render?.status ?? (ready ? "READY" : "NOT_READY");
  return <section id="final-cut" className="export-gate"><div className="section-heading"><div><p className="eyebrow">Export review</p><h2>Final Cut</h2><p>Render only after every narration and shot has been approved.</p></div><span className={`status-badge ${ready ? "status-approved" : "status-pending"}`}>{status === "NOT_READY" ? "Not ready" : status[0] + status.slice(1).toLowerCase()}</span></div><article className="readiness-panel"><div><span>Approved narration</span><strong>{approvedVoices}/{scenes.length}</strong></div><div><span>Approved shots</span><strong>{approvedScenes}/{scenes.length}</strong></div><div><span>All scenes ready</span><strong>{ready ? "Yes" : "Not yet"}</strong></div></article><article className="render-card"><div><p className="eyebrow">Render settings</p><h3>{title}</h3><p className="title-preview">Listen now on Pocket FM</p></div><div><p><b>Scene order</b><br />{scenes.map((scene) => `Scene ${scene.sceneNumber}`).join(" → ") || "No scenes"}</p><label className="music-upload">Optional background music<input ref={musicRef} type="file" accept="audio/mpeg,audio/aac,audio/wav,audio/mp4,.mp3,.m4a,.aac,.wav" onChange={(event) => setMusic(event.target.files?.[0])} /><span>{music?.name ?? "No music selected"}</span></label><label className="subtitle-toggle"><input type="checkbox" checked={subtitles} onChange={(event) => setSubtitles(event.target.checked)} /> Burn subtitles</label><div className="actions"><button onClick={() => void renderTrailer()} disabled={!ready || working}>{working ? "Rendering…" : "Render Final Trailer"}</button></div></div></article>{error && <p className="error" role="alert">{error}</p>}{render?.status === "FAILED" && <p className="error" role="alert">{render.errorMessage}</p>}{render?.status === "COMPLETE" && <div className="final-player"><video controls preload="metadata" src={`/api/renders/${render.id}/video`} /><div><p className="eyebrow">Final trailer</p><p>Duration: {render.durationMs ? `${(render.durationMs / 1000).toFixed(1)} sec` : "—"} · Vertical 9:16</p><a className="button" href={`/api/renders/${render.id}/video`} download={`pocketframe-final-v${render.versionNumber}.mp4`}>Download MP4</a></div></div>}</section>;
}
