"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import type { ProjectReference } from "@/lib/db/repositories";
import type { ProjectReferenceType } from "@/lib/domain/contracts";
import { GuidanceTip } from "@/components/guidance-tip";

type FormValues = { displayName: string; type: ProjectReferenceType; description: string; file?: File };
const categories: ProjectReferenceType[] = ["Character", "Environment", "Prop", "Style"];

export function ReferenceEditDialog({ projectId, reference, onClose }: { projectId: string; reference: ProjectReference; onClose: () => void }) {
  const router = useRouter(); const imageRef = useRef<HTMLInputElement>(null); const [displayName, setDisplayName] = useState(reference.displayName); const [type, setType] = useState<ProjectReferenceType>(reference.type); const [description, setDescription] = useState(reference.description ?? ""); const [working, setWorking] = useState(false); const [error, setError] = useState<string>();
  async function save() { setWorking(true); setError(undefined); const response = await fetch(`/api/projects/${projectId}/references`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ referenceId: reference.id, displayName, type, description }) }); const data = await response.json().catch(() => ({})); setWorking(false); if (!response.ok) return setError(data.error?.message ?? "Could not save reference."); router.refresh(); onClose(); }
  async function replace(file?: File) { if (!file) return; setWorking(true); const form = new FormData(); form.set("file", file); form.set("displayName", displayName); form.set("type", type); form.set("description", description); form.set("replaceId", reference.id); const response = await fetch(`/api/projects/${projectId}/references`, { method: "POST", body: form }); const data = await response.json().catch(() => ({})); setWorking(false); if (!response.ok) return setError(data.error?.message ?? "Could not replace image."); router.refresh(); onClose(); }
  async function remove() { if (!window.confirm(`Remove ${reference.displayName}? It will be removed from scene selections, while existing generated shots remain unchanged.`)) return; setWorking(true); const response = await fetch(`/api/projects/${projectId}/references?referenceId=${encodeURIComponent(reference.id)}`, { method: "DELETE" }); const data = await response.json().catch(() => ({})); setWorking(false); if (!response.ok) return setError(data.error?.message ?? "Could not remove reference."); router.refresh(); onClose(); }
  return <div className="dialog-backdrop" role="presentation"><section className="reference-edit-dialog" role="dialog" aria-modal="true" aria-label="Edit Reference"><div className="section-heading"><div><p className="eyebrow">Reference editor</p><h2>Edit Reference</h2></div><button className="secondary" onClick={onClose} disabled={working}>Close</button></div><div className="reference-editor-content"><Image unoptimized width={96} height={96} src={`/api/projects/${projectId}/references/${reference.id}/image`} alt={reference.displayName} /><div><label>Name<input value={displayName} maxLength={120} onChange={(event) => setDisplayName(event.target.value)} /></label><label>Category<select value={type} onChange={(event) => setType(event.target.value as ProjectReferenceType)}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label></div></div><label>Description<textarea rows={3} value={description} maxLength={500} onChange={(event) => setDescription(event.target.value)} /></label>{error && <p className="error" role="alert">{error}</p>}<input className="visually-hidden" ref={imageRef} type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={(event) => void replace(event.target.files?.[0])} /><div className="actions"><button onClick={() => void save()} disabled={working}>{working ? "Saving…" : "Save Changes"}</button><button className="secondary" onClick={() => imageRef.current?.click()} disabled={working}>Replace Image</button><button className="danger" onClick={() => void remove()} disabled={working}>Remove Reference</button><button className="secondary" onClick={onClose} disabled={working}>Cancel</button></div></section></div>;
}

export function ProjectReferences({ projectId, references }: { projectId: string; references: ProjectReference[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ProjectReference>(); const [working, setWorking] = useState(false); const [error, setError] = useState<string>();
  async function submit(values: FormValues) { if (!values.file) return setError("Choose an image to continue."); setWorking(true); setError(undefined); const form = new FormData(); form.set("file", values.file); form.set("displayName", values.displayName); form.set("type", values.type); form.set("description", values.description); const response = await fetch(`/api/projects/${projectId}/references`, { method: "POST", body: form }); const data = await response.json().catch(() => ({})); setWorking(false); if (!response.ok) return setError(data.error?.message ?? "Could not save this reference."); setOpen(false); router.refresh(); }
  return <section className="project-references-panel"><div className="section-heading"><div><h2>Visual References</h2><p>Add up to three reusable visual references. Choose which scenes use each reference.</p></div><div className="reference-heading-actions"><span className="reference-count">{references.length} of 3 added</span><button type="button" onClick={() => setOpen(true)} disabled={working || references.length >= 3}>Add Reference</button></div></div>{error && <p className="error" role="alert">{error}</p>}{references.length ? <div className="reference-card-grid">{references.map((reference) => <article className="reference-card" key={reference.id}><Image unoptimized width={62} height={62} src={`/api/projects/${projectId}/references/${reference.id}/image`} alt={reference.displayName} /><div className="reference-card-body"><strong>{reference.displayName}</strong><span>{reference.type}</span>{reference.description && <p>{reference.description}</p>}<div className="reference-card-actions"><button type="button" className="secondary" onClick={() => setEditing(reference)} disabled={working}>Edit Reference</button></div></div></article>)}</div> : <p className="reference-empty">No references added. This project will continue without them unless you add one.</p>}{open && <ReferenceUploadForm working={working} onCancel={() => setOpen(false)} onSubmit={submit} />}{editing && <ReferenceEditDialog projectId={projectId} reference={editing} onClose={() => setEditing(undefined)} />}</section>;
}

export function ReferenceUploadForm({ working, onCancel, onSubmit }: { working: boolean; onCancel: () => void; onSubmit: (values: FormValues) => Promise<void> }) {
  const [displayName, setDisplayName] = useState(""); const [type, setType] = useState<ProjectReferenceType>("Character"); const [description, setDescription] = useState(""); const [file, setFile] = useState<File>();
  return <form className="reference-upload-form" onSubmit={(event) => { event.preventDefault(); void onSubmit({ displayName, type, description, file }); }}><strong>Add visual reference</strong><div className="reference-form-grid"><label>Image<input required type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0])} /></label><label>Reference name<input required maxLength={120} value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="e.g. Carter" /></label><label>Category<select value={type} onChange={(event) => setType(event.target.value as ProjectReferenceType)}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Description <small>(optional)</small><input maxLength={500} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Short visual note" /></label></div><div className="actions"><button type="submit" disabled={working}>{working ? "Saving…" : "Add reference"}</button><button type="button" className="secondary" onClick={onCancel} disabled={working}>Cancel</button></div></form>;
}
