"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Scene, SceneVersion } from "@/lib/db/repositories";

type Props = { scenes: Scene[]; versions: Record<string, SceneVersion[]> };
const label: Record<SceneVersion["status"], string> = { QUEUED: "Pending", GENERATING: "Generating", READY: "Generated", APPROVED: "Approved", REJECTED: "Rejected", FAILED: "Failed" };
const seconds = (value: number | null) => value === null ? "—" : `${(value / 1000).toFixed(1)} sec`;

export function ShotSceneCards({ scenes, versions }: Props) {
  const router = useRouter(); const [working, setWorking] = useState<string>(); const [error, setError] = useState<string>();
  const active = Object.values(versions).flat().filter((version) => version.status === "QUEUED" || version.status === "GENERATING").map((version) => version.id).join(",");
  const polling = useRef(false);
  useEffect(() => { if (!active) return; const poll = async () => { if (polling.current) return; polling.current = true; await Promise.all(active.split(",").filter(Boolean).map((id) => fetch(`/api/scene-versions/${id}/status`))); polling.current = false; router.refresh(); }; void poll(); const id = window.setInterval(() => void poll(), 5_000); return () => window.clearInterval(id); }, [active, router]);
  async function json(url: string, init: RequestInit, id: string) { setWorking(id); setError(undefined); const response = await fetch(url, init); const data = await response.json().catch(() => ({})); setWorking(undefined); if (!response.ok) setError(data.error?.message ?? "Shot operation failed."); else router.refresh(); }
  return <section className="voice-section"><div className="section-heading"><div><h2>Shots</h2><p>Generate or upload a version after its narration is approved.</p></div></div>{error && <p className="error" role="alert">{error}</p>}<div className="scene-list">{scenes.map((scene) => <ShotCard key={scene.id} scene={scene} versions={versions[scene.id] ?? []} working={working === scene.id || versions[scene.id]?.some((version) => working === version.id) === true} onAction={json} />)}</div></section>;
}

function ShotCard({ scene, versions, working, onAction }: { scene: Scene; versions: SceneVersion[]; working: boolean; onAction: (url: string, init: RequestInit, id: string) => Promise<void> }) {
  const [prompt, setPrompt] = useState(versions.at(-1)?.prompt ?? scene.promptNotes ?? ""); const [editing, setEditing] = useState(false); const upload = useRef<HTMLInputElement>(null); const latest = versions.at(-1); const ttsApproved = scene.status === "TTS_APPROVED" || ["VIDEO_QUEUED", "VIDEO_GENERATING", "VIDEO_REVIEW", "APPROVED"].includes(scene.status);
  const generate = () => onAction(`/api/scenes/${scene.id}/video`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, provider: "mock" }) }, scene.id);
  const submitUpload = async (file?: File) => { if (!file) return; const form = new FormData(); form.set("file", file); form.set("prompt", prompt); await onAction(`/api/scenes/${scene.id}/upload`, { method: "POST", body: form }, scene.id); if (upload.current) upload.current.value = ""; };
  return <article className="card shot-card"><div className="section-heading"><h3>Scene {String(scene.sceneNumber).padStart(2, "0")}</h3><span className={`badge ${latest ? latest.status.toLowerCase() : "pending"}`}>{latest ? label[latest.status] : "Pending"}</span></div><p className="scene-text"><b>Exact narration:</b> {scene.exactText}</p><label>Visual prompt<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} disabled={working || !ttsApproved || !editing} /></label><p><b>Negative prompt:</b> {latest?.negativePrompt ?? scene.negativePrompt ?? "Applied on generation."}</p><p><b>Camera direction:</b> {scene.cameraIntent ?? "—"} · <b>Target duration:</b> {seconds(scene.targetVideoDurationMs)}</p>{latest?.videoPath && <video controls muted preload="metadata" src={`/api/scene-versions/${latest.id}/video`} />}<p><b>Current version:</b> {latest ? `v${latest.versionNumber} · ${latest.provider}` : "None"}</p><div className="actions"><button onClick={generate} disabled={!ttsApproved || working}>{working ? "Working…" : latest ? "Regenerate" : "Generate"}</button><button onClick={() => setEditing((value) => !value)} disabled={!ttsApproved || working}>{editing ? "Done Editing" : "Edit Prompt"}</button><button onClick={() => upload.current?.click()} disabled={!ttsApproved || working}>Upload Replacement</button><input className="visually-hidden" ref={upload} type="file" accept="video/mp4,.mp4" onChange={(event) => void submitUpload(event.target.files?.[0])} /></div><h4>Version history</h4><ul className="version-history">{versions.length ? versions.map((version) => <li key={version.id}>v{version.versionNumber} · {version.provider} · <span className={`badge ${version.status.toLowerCase()}`}>{label[version.status]}</span>{version.videoPath && <a href={`/api/scene-versions/${version.id}/video`}> Preview</a>}{version.status === "READY" && <span className="actions inline"><button onClick={() => onAction(`/api/scene-versions/${version.id}/approve`, { method: "POST" }, version.id)} disabled={working}>Approve</button><button onClick={() => onAction(`/api/scene-versions/${version.id}/reject`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }, version.id)} disabled={working}>Reject</button></span>}{version.errorMessage && <small className="error"> {version.errorMessage}</small>}</li>) : <li>No versions yet.</li>}</ul></article>;
}
