"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AudioVersion, Scene } from "@/lib/db/repositories";
import type { VoiceBible } from "@/lib/domain/contracts";
import { BeginnerHint, StageProgressList, StageStatus, SubStageTabs } from "@/components/production-experience";

type Props = { scenes: Scene[]; audioVersions: Record<string, AudioVersion[]>; voiceBible: VoiceBible | null };
const seconds = (value: number | null) => value === null ? "—" : `${(value / 1000).toFixed(1)} sec`;

export function VoiceSceneCards({ scenes, audioVersions, voiceBible }: Props) {
  const router = useRouter(); const [working, setWorking] = useState<string>(); const [error, setError] = useState<string>(); const [selectedSceneId, setSelectedSceneId] = useState(scenes[0]?.id);
  async function generate(scene: Scene, deliveryPrompt: string) { setWorking(scene.id); setError(undefined); const response = await fetch(`/api/scenes/${scene.id}/tts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ deliveryPrompt, quality: "preview" }) }); const data = await response.json(); setWorking(undefined); if (!response.ok) return setError(data.error?.message ?? "Could not generate audio."); router.refresh(); }
  async function approve(sceneId: string) { setWorking(sceneId); setError(undefined); const response = await fetch(`/api/scenes/${sceneId}/approve-tts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ approved: true }) }); const data = await response.json(); setWorking(undefined); if (!response.ok) return setError(data.error?.message ?? "Could not approve audio."); router.refresh(); }
  const approvedCount = scenes.filter((scene) => audioVersions[scene.id]?.some((version) => version.status === "APPROVED")).length;
  const readyCount = scenes.filter((scene) => audioVersions[scene.id]?.some((version) => version.status === "READY")).length;
  const pendingCount = scenes.length - approvedCount - readyCount;
  const selectedScene = scenes.find((scene) => scene.id === selectedSceneId) ?? scenes[0];
  const direction = <section className="voice-direction"><div className="section-heading"><div><p className="eyebrow">Voice Direction</p><h2>Voice Bible</h2><p>One narrator, directed with a consistent tone across each exact-text scene.</p></div></div>{voiceBible ? <article className="voice-bible"><div><strong>{voiceBible.narratorPersona}</strong><span>{voiceBible.voiceStyle}</span></div><dl><VoiceField label="Tone" value={voiceBible.tone} /><VoiceField label="Pace" value={voiceBible.baselinePace} /><VoiceField label="Language" value={voiceBible.languageCode} /><VoiceField label="Provider" value={voiceBible.ttsProvider} /><VoiceField label="Pronunciation" value={voiceBible.pronunciationNotes || "No special notes"} /></dl></article> : <p className="empty-state">Voice direction becomes available after Story Planning.</p>}</section>;
  const generation = <section className="narration-generation"><div className="section-heading"><div><p className="eyebrow">Narration Generation</p><h2>Generate scene narration</h2><p>Generate one scene at a time so every performance remains easy to review.</p></div></div><div className="generation-queue">{scenes.map((scene) => { const latest = audioVersions[scene.id]?.at(-1); const approved = audioVersions[scene.id]?.some((version) => version.status === "APPROVED"); return <div className="generation-row" key={scene.id}><strong>Scene {String(scene.sceneNumber).padStart(2, "0")}</strong><span>{scene.emotion ?? "Direction pending"}</span><StageStatus status={approved ? "Complete" : latest ? "Review Required" : "Ready"} /><button onClick={() => generate(scene, scene.deliveryPrompt ?? "")} disabled={working === scene.id || approved}>{working === scene.id ? "Generating…" : latest ? "Regenerate" : "Generate"}</button></div>; })}</div></section>;
  const review = <section className="narration-review"><div className="section-heading"><div><p className="eyebrow">Narration Review</p><h2>Listen and approve one scene</h2><p>Exact narration cannot be edited here; only performance direction can change.</p></div></div><div className="scene-selector" role="tablist" aria-label="Narration scenes">{scenes.map((scene) => <button type="button" role="tab" aria-selected={selectedScene?.id === scene.id} className={selectedScene?.id === scene.id ? "selected" : "secondary"} onClick={() => setSelectedSceneId(scene.id)} key={scene.id}>Scene {scene.sceneNumber}</button>)}</div>{selectedScene && <VoiceCard scene={selectedScene} latest={audioVersions[selectedScene.id]?.at(-1)} approved={audioVersions[selectedScene.id]?.some((version) => version.status === "APPROVED") ?? false} working={working === selectedScene.id} onGenerate={generate} onApprove={approve} />}</section>;
  return <section id="voice" className="voice-section"><BeginnerHint>Generate narration from the exact synopsis text. Approve each scene before moving on to shots.</BeginnerHint><StageProgressList items={[{ label: `${scenes.length} scenes`, status: "Complete" }, { label: `${approvedCount} approved`, status: approvedCount === scenes.length && scenes.length > 0 ? "Complete" : "Waiting" }, { label: `${readyCount} ready for review`, status: readyCount ? "Review Required" : "Waiting" }, { label: `${pendingCount} pending`, status: pendingCount ? "Waiting" : "Complete" }]} />{error && <p className="error" role="alert">{error}</p>}<SubStageTabs label="Voice stages" stages={[{ id: "direction", label: "Voice Direction", status: voiceBible ? "Complete" : "Blocked", content: direction }, { id: "generation", label: "Narration Generation", status: pendingCount ? "Ready" : readyCount ? "Review Required" : "Complete", content: generation }, { id: "review", label: "Narration Review", status: readyCount ? "Review Required" : approvedCount === scenes.length && scenes.length > 0 ? "Complete" : "Waiting", content: review }]} /></section>;
}

function VoiceField({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function VoiceCard({ scene, latest, approved, working, onGenerate, onApprove }: { scene: Scene; latest?: AudioVersion; approved: boolean; working: boolean; onGenerate: (scene: Scene, prompt: string) => void; onApprove: (sceneId: string) => void }) { const [prompt, setPrompt] = useState(scene.deliveryPrompt ?? ""); return <article className={`voice-review-card ${approved ? "is-approved" : ""}`}><div className="voice-row-summary"><strong>Scene {String(scene.sceneNumber).padStart(2, "0")}</strong><p>{scene.exactText}</p><span>{scene.emotion}</span><span>{scene.pace}</span><span>{seconds(scene.ttsDurationMs)}</span><span className={`status-badge ${approved ? "status-approved" : latest ? "status-generated" : "status-pending"}`}>{approved ? "Approved" : latest ? "Ready for review" : "Pending"}</span></div><div className="voice-review-actions actions">{latest && <a className="button secondary" href={`/api/audio-versions/${latest.id}`}>Play narration</a>}<button onClick={() => onGenerate(scene, prompt)} disabled={working}>{working ? "Generating…" : latest ? "Regenerate narration" : "Generate narration"}</button>{latest && <button className="secondary" onClick={() => onApprove(scene.id)} disabled={working || approved}>{approved ? "Narration approved" : "Approve narration"}</button>}</div><details><summary>Performance direction and version history</summary><label>Delivery direction<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} disabled={working} /></label><p className="duration-line"><b>Target visual duration:</b> {seconds(scene.targetVideoDurationMs)}</p>{latest && <small>Audio version {latest.versionNumber} · {latest.provider} / {latest.model}</small>}</details></article>; }
